apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: todo-backend
    newName: bachthyaglx/todo-backend:latest
