apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - persistenceVolume.yaml
  - persistenceVolumeClaim.yaml
images:
  - name: todo-app
    newName: bachthyaglx/todo-app:latest
